data:
  local_raw_path: "data/raw/telco_churn_raw.csv"
  local_clean_path: "data/clean/telco_churn_clean.csv"
  azure_container: "ml-data"
  azure_clean_blob_name: "telco_churn_clean.csv"

split:
  train_fraction: 0.7
  val_fraction: 0.15
  test_fraction: 0.15
  random_state: 42

model:
  type: "random_forest"
  params:
    n_estimators: 300
    max_depth: 8
    min_samples_split: 4
    min_samples_leaf: 2
    random_state: 42
    n_jobs: -1

wandb:
  use_wandb: true
  project_name: "azure-churn-mlops"
  entity: null

azure:
  blob_connection_string_env_var: "AZURE_BLOB_CONNECTION_STRING"
  model_container: "ml-models"
  model_blob_name: "random_forest_churn_model.pkl"
  preprocessor_blob_name: "preprocessor.pkl"

api:
  host: "0.0.0.0"
  port: 8000
